# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -Xms4G
org.gradle.parallel=true

downloadJavadoc=true
downloadSources=true

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.0.1
maven_group=bid.yuanlu.seedmap4xaero
archives_base_name=seed-map-for-xaero

# Dependencies
fabric_api_version=0.153.0+26.1.2
xaero_map_version=1.41.0
xaero_lib_version=1.1.17
mod_publish_plugin_version=1.1.0